# MySQL address, user and password
# user must have replication privilege in MySQL.
my_addr = "127.0.0.1:3306"
my_user = "root"
my_pass = ""

# Elasticsearch address
es_addr = "127.0.0.1:9200"

# Path to store data, like master.info, and dump MySQL data 
data_dir = "./var"

# Inner Http status address
stat_addr = "127.0.0.1:12800"

# pseudo server id like a slave 
server_id = 1001

# mysql or mariadb
flavor = "mysql"

# mysqldump execution path
# if not set or empty, ignore mysqldump.
mysqldump = "mysqldump"

# MySQL data source
[[source]]
schema = "linuxman"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["article", "keyword"]

# Below is for special rule mapping
[[rule]]
schema = "linuxman"
table = "article"
index = "developerq_article"
type = "0"
#filter = ["uk", "tags", "title_raw", "title_cn_raw", "question_raw", "question_cn_raw", "answer_raw", "answer_cn_raw"]

# Below is for special rule mapping
[[rule]]
schema = "linuxman"
table = "keyword"
index = "developerq_keyword"
type = "0"

[[source]]
schema = "baidu"

# Only below tables will be synced into Elasticsearch.
# "test_river_[0-9]{4}" is a wildcard table format, you can use it if you have many sub tables, like table_0000 - table_1023
# I don't think it is necessary to sync all tables in a database.
tables = ["uinfo", "sharedata", "keyword"]

# Below is for special rule mapping
[[rule]]
schema = "baidu"
table = "keyword"
index = "bilisou_keyword"
type = "0"


# Below is for special rule mapping
[[rule]]
schema = "baidu"
table = "uinfo"
index = "bilisou_uinfo"
type = "0"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    [rule.field]
    # This will map column title to elastic search my_title
    title="uname"
    # This will map column tags to elastic search my_tags and use array type
    #_id="uk"

# wildcard table rule, the wildcard table must be in source tables
[[rule]]
schema = "baidu"
table = "sharedata"
index = "bilisou_sharedata"
type = "0"

    # title is MySQL test_river field name, es_title is the customized name in Elasticsearch
    [[rule.fields]]
    title = "title"
    #_id="dataid"

